
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_db
    username: root
    password: 1026
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect